### ISSUE TITLE
blackscreen and dependency failures on update

### ISSUE THREAD

**Issue by jsox79** [AchillesPunks/skin.titan.bingie.mod#5]
started getting a blackscreen after awhile.  went to research what was causing it notice under updates that titan bingie along with several supporting addons had updates.  they all crash saying dependency failed.  ive tried installing one by one, but they all complain about the dependency not being met.
the addons in question are
metadata and artwork module
skin helper service
skin helper service widgets
the tvdb api v2
titan bingie mod
repository version is 1.0

**Comment by matke-84** [comment]
It is recommended to install everything from scratch. I know it sucks, but it's kind of the safest way. There were also small problems in the repository that should have been solved now.
