### ISSUE TITLE
Add addon to search

### ISSUE THREAD

**Issue by jsox79** [AchillesPunks/skin.titan.bingie.mod#6]
I had this working in last build but you changed the structure.  Any pointers on how I should add it now, the old format no longer works, I'm thinking maybe because of conditional toggles in the bingie search menu?

**Comment by matke-84** [comment]
Not sure what you want? Addon search is working.

**Comment by jsox79** [comment]
Not search for addons, but within an addon.

**Comment by matke-84** [comment]
I still don't understand. TBM has always only been able to search local library, youtube and addons. Since this version, it has been able to search the tmdb helper. So not a single function was abolished, but one was added.

**Comment by jsox79** [comment]
i figured it out, it was a format error on my part.  needed to set to has.focus.  
i was trying to add my own plugin://  thanks
